enum MRPCs
{
	RPC_CLIENT_REQUEST_TELEPORT = 1337,
	RPC_CLIENT_REQUEST_GODMODE_TOGGLE,
	RPC_CLIENT_REQUEST_INVISIBLE_TOGGLE,
	RPC_CLIENT_REQUEST_SPAWN_INFECTED,
	RPC_CLIENT_REQUEST_SPAWN_WOLFIE,
	RPC_CLIENT_REQUEST_KDEV_TP,
	RPC_CLIENT_REQUEST_FREEZE,
	RPC_SERVER_REQUEST_INVISIBILITY,
	RPC_SERVER_REQUEST_ADMINITY,
	DEV_RPC_SPAWN_ITEM,
	RPC_CLIENT_REQUEST_DESPAWN_ITEM,
	RPC_CLIENT_REQUEST_TELEPORT_TO_PLAYER,
	RPC_CLIENT_REQUEST_TELEPORT_PLAYER_TO_ME,
	RPC_SERVER_MSG,
	RPC_SERVER_RECEIVE_CAM_POS
}
